### ISSUE TITLE
Wrong route for css and js

### ISSUE THREAD

**Issue by ezeveliz** [speniti/laravel-mix-workbox#1]
After compiling, the manifest line looks like this: 

`Object(workbox_precaching_precacheAndRoute__WEBPACK_IMPORTED_MODULE_1__["precacheAndRoute"])([{'revision':'7cab58508017b184d0f25707188bcee0','url':'//css/app.css'},{'revision':'5708fbfc3cf0f5992f08a6d48d898f87','url':'//js/app.js'}]);`

The problem is the double slash before the css and js folders, it throws an error saying failed to fetch:

![error (4)](https://user-images.githubusercontent.com/24837065/76690300-6bfc4100-661d-11ea-8c89-c078a1cf51b9.png)

PS: before I used the workbox plugin for webpack, but it was the same

**Comment by speniti** [comment]
Seems an issue related to webpack configuration not to the plugin. 
I had the same problem i was able to fix it by setting the outputPath as an empty string.
Try to append the following lines to your `webpack.mix.js`

```js
.webpackConfig({
    output: { publicPath: '' }
})
```
