### ISSUE TITLE
precached. Configure maximumFileSizeToCacheInBytes to change this limit

### ISSUE THREAD

**Issue by 33sKamal** [speniti/laravel-mix-workbox#2]
hello 
how i can update precached. Configure maximumFileSizeToCacheInBytes to change this limit

**Comment by speniti** [comment]
Hi! I'm not 100% sure to have fully understood your question. 
But if you need to customize that value as mentioned in the [docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#InjectManifest) you can simply add the key `maximumFileSizeToCacheInBytes` in the configuration object like this:
```js
// webpack.mix.js

let mix = require('laravel-mix');

require('laravel-mix-workbox');

mix
    .js('resources/js/app.js', 'public/js')
    .less('resources/less/app.less', 'public/css')
    .injectManifest({
      swSrc: './resources/js/service-worker.js',
      maximumFileSizeToCacheInBytes: 1024
    });
```
You need to specify the maximum size in bytes. In the example before i set it to 1M. You have to figure out what value fits for your build.
