### ISSUE TITLE
Webpack compiling in production with workbox

### ISSUE THREAD

**Issue by FelixINX** [speniti/laravel-mix-workbox#5]
Hi!

I am looking for some guidance on how to use laravel-mix-workbox for deployment in production environnement, **while running `npm run production` on the production server or CD**. I had issues in the past where I had `loading chuck failed` error.

What files should I ignore or keep ?

Thanks!

**Comment by speniti** [comment]
Hi! 
I know i'm terribly in late but 2020 was such a crazy year and I hadn't enough time to maintain this project.
Are you still facing this issue?

**Comment by FelixINX** [comment]
Hi!

No worries, 2020 has been a crazy year for everyone!

I don't use the plugin anymore, I have moved my frontend to a dedicated app. I just tested with a fresh app using the latest version of everything and there is no problem so far.

Thank you!
