### ISSUE TITLE
 Double slash in url to resources

### ISSUE THREAD

**Issue by Blazheiko** [speniti/laravel-mix-workbox#6]
Hi, thanks for the extension. Help me understand why when generating the public / service-worker.js file in the url field, two //?
`Object(workbox_precaching__WEBPACK_IMPORTED_MODULE_0__["precacheAndRoute"])([{'revision':'06df4f4173949b061ade3ae814fb9cc0','url':'//assets/css/app.css'},{'revision':'740fd697b8866b74cd7b8f669ddfbe6f','url':'//assets/css/styles.css'},{'revision':'21bae4ecf78d79fd154031c710bdc3a1','url':'//js/app.js'},{'revision':'af92f221c524c24ee9b3ee3f8f9ccb5b','url':'//js/manifest.js'},{'revision':'d00b83cc3284f2145135d02953b02f38','url':'//js/vendor.js'}] || []); `

**Comment by Blazheiko** [comment]
it's easy
`mix.webpackConfig({
    output: {
        publicPath: ''
    },
})
.injectManifest({
    swSrc: './resources/js/service-worker.js',
    maximumFileSizeToCacheInBytes:6291456
});`

**Comment by ardavan-ansari** [comment]
I had the same problem, I fixed it with the following option: 
` .generateSW({
        modifyURLPrefix: {
            '//': process.env.APP_URL + "/",
        },`

**Comment by ardavn** [comment]
Had the same issue, was able to fix with the following option:
`.generateSW({
     modifyURLPrefix: { 
      '//': process.env.APP_URL + "/" 
     }
  })`
