### ISSUE TITLE
Add laravel-mix ^6.0.0 as peer dependencies

### ISSUE THREAD

**Issue by mikkellindblom** [speniti/laravel-mix-workbox#7]
Hi,

Thank you for the mix extension, we use it across all of our projects.

Would you be so kind to add support for laravel-mix ^6.0.0?

**Comment by speniti** [comment]
Hi @mikkellindblom i've added a pull request to fix the issue. 
I'd be glad to have your feedback before i release it.

Thank you! 😄

**Comment by mikkellindblom** [comment]
Hi @speniti, the PR looks solid. 

Thank you so much for the speedy reply.
